### ISSUE TITLE
executeCallbacks() loop error

### ISSUE THREAD

**Issue by seggev319** [bvaughn/task-runner#2]
I kept getting an error saying "Cannot read property 'execute' of undefined" until I changed this line:
`for (var i = 0, length = taskCallbacks.length; i < length; i++)`
int this:
`for (var i = 0; i < taskCallbacks.length; i++)`
In Abstract.prototype.executeCallbacks, /dist/task-runner.js, line 261

Please look into this.

**Comment by bvaughn** [comment]
Need repro steps. This looks like insufficient info.
